### ISSUE TITLE
Missing RBO Files

### ISSUE THREAD

**Issue by plSln** [npalardy/CSVParser#1]
Hey,

i just downloaded as ZIP and tried to open. Seems that the repository is incomplete at the moment.

Following files are missing:
CSVField.rbo
CSVParser.rbo
CSVRecordSet.rbo

![Bildschirmfoto 2019-10-14 um 17 54 43](https://user-images.githubusercontent.com/42576323/66765235-c432e980-eeab-11e9-8a32-c621c768276d.png)

**Comment by npalardy** [comment]
> On Oct 14, 2019, at 5:55 PM, Philipp Lange <notifications@github.com> wrote:
> 
> Hey,
> 
> i just downloaded as ZIP and tried to open. Seems that the repository is incomplete at the moment.

should be fixed if you grab the ZIP again

**Comment by plSln** [comment]
thx, is fixed
